# Generated by Django 2.2.3 on 2019-07-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member1Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'member1model',
            },
        ),
    ]
