# Generated by Django 2.2.3 on 2019-07-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member1model',
            name='state',
            field=models.CharField(choices=[('Y', '正常'), ('F', '冻结')], default='Y', max_length=3),
        ),
    ]
