# Generated by Django 2.2.3 on 2019-07-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_member1model_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member1model',
            name='state',
            field=models.CharField(choices=[('Y', '正常'), ('F', '冻结')], default='正常', max_length=3),
        ),
    ]
